# file name:screen.kv
<MainScreen>:
    Button:
        text:"Enter sub View"
        size_hint: None, None
        pos_hint: {'right': 1,'top':1}
        size: 150, 50
        on_press:root.manager.current="sub"
    Label:
        size_hint: None, None
        pos_hint: {'left': 1,'top':1}
        size: 150, 50
        text:"Main"
    Label:
        text: root.ran_no
        font_size:15
        pos:120, 186
        size_hint:None,None
        color: 1, 1, 1, 1
        text_size:300, 90
        halign:'left'
        valign:'top'
    Label:
        text: root.his_no
        font_size:15
        pos:120, 93
        size_hint:None,None
        color: 1, 1, 1, 1
        text_size:300, 90
        halign:'left'
        valign:'top'
    Label:
        text: root.his_no_sort
        font_size:15
        pos:120, 0
        size_hint:None,None
        color: 1, 1, 1, 1
        text_size:300, 90
        halign:'left'
        valign:'top'


<SubScreen>:
    Button:
        size_hint: None, None
        pos_hint: {'right': 1,'top':1}
        size: 150, 50
        text:"Return"
        on_press:root.manager.current="main"
    Label:
        text:"Sub"
        size_hint: None, None
        pos_hint: {'left': 1,'top':1}
        size: 150, 50
