#:kivy 1.10.1
#:import datetime datetime

RootWidget:
    # import container
    container: container

    # fill the container
    BoxLayout:
        id: container
        orientation: 'horizontal'
        padding: 800  # decide Label's Y_position
        spacing: 940
        canvas:
            Color:
                rgba: 0, 0, 0, root.clearnot_color
        #Label:
        #    text: 'clearnot2'
        #    font_size:50
        #    color:1, 1, 1, 1
