#:kivy 1.8.0
#:import datetime datetime

RootWidget:
    # import container
    container: container

    # fill the container
    BoxLayout:
        id: container
        orientation: 'horizontal'
        padding: 0
        spacing: 3

        Label:
            text: 'Clear Or Not'
            font_size:20
            pos:200, 200

            # weiter button
            Button:
                size_hint: 0.2, 1
                pos:2, 2
                text: 'Back'
                on_release: root.next_screen('randomno')

            Button:
                id: clear
                size_hint: 0.2, 1
                pos:100, 100
                text: 'Clear'
                on_release: root.confim2()
